# conda build -c conda-forge --python 3.7 recipe/

package:
  name: metagraph
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: py{{ PY_VER }}h{{ PKG_HASH }}_{{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}

requirements:
  host:
    - python
    - setuptools
    - importlib_metadata
    - numpy
    - scipy
    - donfig

  run:
    - python
    - setuptools
    - importlib_metadata
    - numpy
    - scipy
    - donfig

test:
  requires:
    - pytest
    - numpy
    - scipy
    - networkx
    - grblas
    - pandas
    - python-louvain
#    - pytest-cov
#    - coverage
#    - black

  commands:
    - pytest --pyargs metagraph.tests

about:
  home: https://github.com/ContinuumIO/metagraph
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Graph algorithm solver across multiple hardware backends'
  description: |
    Python library for running graph algorithms on a variety of hardware backends.
    Data representing the graph will be automatically converted between available hardware options
    to find an efficient solution.
  dev_url: https://github.com/ContinuumIO/metagraph
