name: mg
dependencies:
# dev environment
  - python=3.8
  - coverage
  - pytest
  - pytest-cov
  - black
  - conda-forge::pre-commit
  - python-graphviz

# documentation
  - sphinx=3.0.4
  - nbsphinx
  - notebook
  - conda-forge::pydata-sphinx-theme
  - matplotlib
  - pip
  - pip:
    - rst2pdf
    - nest_asyncio

# metagraph dependencies (so setup.py develop doesn't pip install them)
  - importlib_metadata
  - numpy
  - networkx
  - pandas
  - scipy>=1.8.0
  - scikit-learn
  - dask==2021.10.0
  - conda-forge::distributed
  - conda-forge::donfig
  - conda-forge::grblas
  - conda-forge::python-louvain
  - conda-forge::websockets
