name: mg
dependencies:
# dev environment
  - python=3.8
  - python-graphviz

# documentation
  - sphinx=3.0.4
  - nbsphinx
  - notebook
  - conda-forge::pydata-sphinx-theme
  - dask
  - distributed
  - pip
  - pip:
    - rst2pdf
