name: mg
dependencies:
# dev environment
  - python=3.8
  - coverage
  - pytest
  - pytest-cov
  - black
  - python-graphviz

# metagraph dependencies (so setup.py develop doesn't pip install them)
  - dask
  - numpy
  - networkx>=2.5.1
  - pandas
  - scipy
  - scikit-learn
  - conda-forge::donfig
  - conda-forge::grblas
  - conda-forge::python-louvain
  - conda-forge::websockets
