package:
   name: metagraph
   version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown') }}

source:
   path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}
  string: {{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python >=3.7
  run:
    - python >=3.7
    - importlib_metadata
    - numpy >=1.15
    - networkx
    - pandas
    - python-louvain
    - scipy
    - scikit-learn
    - donfig
    - grblas >=1.3.2
    - dask
    - python-graphviz
    - nest-asyncio

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
    - scikit-learn
    - black >=20.8b1
  commands:
    - py.test --cov-report term-missing --cov=metagraph --pyargs metagraph.tests

about:
  home: https://github.com/metagraph-dev/metagraph
  license: Apache2
  license_file: LICENSE
  summary: Run graph algorithms on many backends
